backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "services"
    label: "الخدمات"
    file: "src/data/services.json"
    widget: "list"
    fields:
      - {label: "المعرف", name: "id", widget: "string"}
      - {label: "اسم الخدمة", name: "name", widget: "string"}
      - {label: "الوصف", name: "description", widget: "text"}
      - {label: "السعر", name: "price", widget: "string"}
      - {label: "السعر الأصلي", name: "original_price", widget: "string"}
      - {label: "اللون", name: "color", widget: "string", default: "bg-blue-500"}
      - {label: "الميزات", name: "features", widget: "list", default: [""]}
      - {label: "صورة الشعار", name: "logo_url", widget: "image", required: false}
